# postgres
version: '3'
services:
    postgres: 
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
#    pgadmin:
#        image: dpage/pgadmin4
#        restart: always
#        environment:
#            PGADMIN_DEFAULT_EMAIL: dillbob@gmail.com
#            PGADMIN_DEFAULT_PASSWORD: secret
#            PGADMIN_LISTEN_PORT: 80
#        ports:
#        - "6351:80"
    redis: 
        image: 'redis:latest'
    api:
        depends_on: 
            - postgres
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        depends_on: 
            - postgres
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app
    worker:
        restart: on-failure
        depends_on: 
            - redis
            - postgres
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /usr/app/node_modules
            - ./worker:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        depends_on:
            - api
            - client
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '6350:80'


        